apiVersion: v1
kind: Service
metadata:
  name: amazon-app-service
  namespace: amazon-ns
  labels:
    app.kubernetes.io/name: amazon-app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: amazon-app
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP